// T1.P1 (v1.5.5-beta2): FFI symbol surface audit. Every ghita_engine_*
// string in native_bindings.dart must be a symbol of the audited ABI
// (docs/rust_engine_abi.md). _tryLookup silently falls back on unknown
// symbols — this test makes a typo/new lookup fail loudly instead.
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

void main() {
  test('FFI surface audit: every lookup is an audited ABI symbol', () {
    final src = File('lib/src/ffi/native_bindings.dart').readAsStringSync();
    final lookups = RegExp('ghita_engine_[a-z0-9_]+')
        .allMatches(src)
        .map((m) => m.group(0)!)
        .toSet();
    const known = {
      'ghita_engine_add_audio_effect',
      'ghita_engine_add_bookmark',
      'ghita_engine_add_clip',
      'ghita_engine_add_clip_keyframe',
      'ghita_engine_add_keyframe_ex',
      'ghita_engine_add_spectral_edit',
      'ghita_engine_add_speed_ramp_point',
      'ghita_engine_apply_color_correction',
      'ghita_engine_apply_filter',
      'ghita_engine_cache_stats',
      'ghita_engine_cancel_export',
      'ghita_engine_clear_audio_effects',
      'ghita_engine_clear_clip_keyframes',
      'ghita_engine_clear_clips',
      'ghita_engine_clear_selection',
      'ghita_engine_clear_spectral_edits',
      'ghita_engine_clear_speed_curve',
      'ghita_engine_copy_keyframes',
      'ghita_engine_create',
      'ghita_engine_destroy',
      'ghita_engine_detect_tempo',
      'ghita_engine_export_labels',
      'ghita_engine_get_audio_waveform',
      'ghita_engine_get_audio_waveform_peaks',
      'ghita_engine_get_available_filters',
      'ghita_engine_get_beat_times',
      'ghita_engine_get_bookmark_count',
      'ghita_engine_get_bookmarks_json',
      'ghita_engine_get_clip_count',
      'ghita_engine_get_clip_keyframe_count',
      'ghita_engine_get_clip_keyframe_interpolation',
      'ghita_engine_get_direct_buffer',
      'ghita_engine_get_duration_ms',
      'ghita_engine_get_export_file_size',
      'ghita_engine_get_export_progress',
      'ghita_engine_get_gain_reduction_db',
      'ghita_engine_get_mask_buffer',
      'ghita_engine_get_media_height',
      'ghita_engine_get_media_info',
      'ghita_engine_get_media_width',
      'ghita_engine_get_playback_rate',
      'ghita_engine_get_position_ms',
      'ghita_engine_get_snapping_fps',
      'ghita_engine_get_spectrogram',
      'ghita_engine_get_thumbnail',
      'ghita_engine_get_timeline_rms',
      'ghita_engine_get_timeline_waveform',
      'ghita_engine_get_version',
      'ghita_engine_gpu_enabled',
      'ghita_engine_gpu_stats',
      'ghita_engine_graph_add_node',
      'ghita_engine_graph_clear',
      'ghita_engine_graph_get_json',
      'ghita_engine_graph_remove_last',
      'ghita_engine_has_clip',
      'ghita_engine_has_ffmpeg',
      'ghita_engine_import_transcript',
      'ghita_engine_init',
      'ghita_engine_is_exporting',
      'ghita_engine_is_playing',
      'ghita_engine_is_recording',
      'ghita_engine_load_media',
      'ghita_engine_mix_audio_window',
      'ghita_engine_modify_mask',
      'ghita_engine_paint_brush_stroke',
      'ghita_engine_paint_clone',
      'ghita_engine_paint_heal',
      'ghita_engine_pause',
      'ghita_engine_play',
      'ghita_engine_remove_audio_effect',
      'ghita_engine_remove_bookmark',
      'ghita_engine_remove_clip',
      'ghita_engine_render_frame_at',
      'ghita_engine_render_frame_at_ex',
      'ghita_engine_render_frame_rgba',
      'ghita_engine_render_pip',
      'ghita_engine_render_text_overlay',
      'ghita_engine_resample_waveform',
      'ghita_engine_seek',
      'ghita_engine_set_audio_effect_param',
      'ghita_engine_set_audio_preview_enabled',
      'ghita_engine_set_canvas_background',
      'ghita_engine_set_clip_blend_mode',
      'ghita_engine_set_clip_color_correction',
      'ghita_engine_set_clip_filter',
      'ghita_engine_set_clip_font',
      'ghita_engine_set_clip_keyframe_interpolation',
      'ghita_engine_set_clip_maintain_pitch',
      'ghita_engine_set_clip_mask',
      'ghita_engine_set_clip_pip',
      'ghita_engine_set_clip_pitch',
      'ghita_engine_set_clip_position',
      'ghita_engine_set_clip_sticker_transform',
      'ghita_engine_set_clip_text',
      'ghita_engine_set_clip_transition',
      'ghita_engine_set_export_channel_layout',
      'ghita_engine_set_filter_preset',
      'ghita_engine_set_gpu_enabled',
      'ghita_engine_set_keyframe_bezier',
      'ghita_engine_set_loop_region',
      'ghita_engine_set_noise_suppress',
      'ghita_engine_set_playback_rate',
      'ghita_engine_set_preview_pitch_preserve',
      'ghita_engine_set_selection_ellipse',
      'ghita_engine_set_selection_lasso',
      'ghita_engine_set_selection_magic_wand',
      'ghita_engine_set_selection_rect',
      'ghita_engine_set_snapping_fps',
      'ghita_engine_set_time_signature',
      'ghita_engine_set_track_state',
      'ghita_engine_set_volume',
      'ghita_engine_start_export',
      'ghita_engine_start_export_ex',
      'ghita_engine_start_recording',
      'ghita_engine_stop_recording',
      'ghita_engine_upsert_clip',
    };
    final unknown = lookups.difference(known);
    expect(unknown, isEmpty,
        reason: 'unknown FFI symbol(s) — add to docs/rust_engine_abi.md + the audit list: $unknown');
  });
}
